create extension if not exists pgcrypto;

create table public.profiles (user_id uuid primary key references auth.users(id) on delete cascade, bakery_name text not null default 'My Bakery', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.planner_settings (user_id uuid primary key references auth.users(id) on delete cascade, starter_hydration numeric not null default 1 check (starter_hydration > 0 and starter_hydration <= 3), shopping_buffer numeric not null default .1 check (shopping_buffer between 0 and 1), packaging_buffer numeric not null default .1 check (packaging_buffer between 0 and 1), mixer_capacity_grams numeric not null default 15000 check (mixer_capacity_grams > 0), starter_seed_parts numeric not null default 1, starter_flour_parts numeric not null default 2, starter_water_parts numeric not null default 2);
create table public.recipes (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null check (char_length(name) between 1 and 120), category text not null default 'Bread', yield_per_batch numeric not null check (yield_per_batch > 0), yield_label text not null, mixer_dough_grams numeric not null default 0 check (mixer_dough_grams >= 0), oven_capacity numeric not null default 1 check (oven_capacity > 0), cycle_minutes integer not null default 30 check (cycle_minutes > 0), notes text not null default '', archived_at timestamptz, version integer not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create type public.ingredient_role as enum ('flour','water','active_starter','discard','inclusion','other');
create table public.recipe_ingredients (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, recipe_id uuid not null references public.recipes(id) on delete cascade, name text not null check (char_length(name) between 1 and 120), grams numeric not null check (grams >= 0), role public.ingredient_role not null default 'other', package_grams numeric check (package_grams > 0), sort_order integer not null default 0);
create table public.equipment (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null, kind text not null check (kind in ('mixer','oven','other')), capacity numeric not null check (capacity > 0), cycle_minutes integer check (cycle_minutes > 0));
create table public.events (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, name text not null check (char_length(name) between 1 and 120), event_at timestamptz, status text not null default 'draft' check (status in ('draft','finalized','archived')), shopping_buffer numeric not null default .1, packaging_buffer numeric not null default .1, starter_hydration numeric not null default 1, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.event_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, event_id uuid not null references public.events(id) on delete cascade, recipe_id uuid references public.recipes(id) on delete set null, recipe_snapshot jsonb not null, target numeric not null check (target >= 0), batch_policy text not null default 'whole' check (batch_policy in ('whole','exact')), sort_order integer not null default 0);
create table public.mixer_loads (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, event_id uuid not null references public.events(id) on delete cascade, load_number integer not null check (load_number > 0), capacity_grams numeric not null check (capacity_grams > 0), unique(event_id, load_number));
create table public.mixer_load_items (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, mixer_load_id uuid not null references public.mixer_loads(id) on delete cascade, event_item_id uuid not null references public.event_items(id) on delete cascade, units numeric not null check (units > 0));
create table public.schedule_blocks (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, event_id uuid not null references public.events(id) on delete cascade, day_label text not null, title text not null, notes text not null default '', sort_order integer not null default 0);
create table public.packaging_plans (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, event_item_id uuid not null references public.event_items(id) on delete cascade unique, units_per_package numeric not null default 1 check (units_per_package > 0), packed numeric not null default 0, loaded numeric not null default 0, notes text not null default '');
create table public.google_connections (user_id uuid primary key references auth.users(id) on delete cascade, encrypted_refresh_token text not null, scopes text[] not null default '{}', connected_at timestamptz not null default now());
create table public.google_exports (id uuid primary key default gen_random_uuid(), user_id uuid not null references auth.users(id) on delete cascade, event_id uuid not null references public.events(id) on delete cascade, kind text not null check (kind in ('doc','sheet')), google_file_id text not null, google_file_url text not null, exported_at timestamptz not null default now());

create index recipes_user_idx on public.recipes(user_id);
create index events_user_idx on public.events(user_id);
create index event_items_event_idx on public.event_items(event_id);

do $$ declare table_name text; begin foreach table_name in array array['profiles','planner_settings','recipes','recipe_ingredients','equipment','events','event_items','mixer_loads','mixer_load_items','schedule_blocks','packaging_plans','google_connections','google_exports'] loop execute format('alter table public.%I enable row level security', table_name); execute format('create policy %I on public.%I for all using (auth.uid() = user_id) with check (auth.uid() = user_id)', table_name || '_owner', table_name); end loop; end $$;

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles(user_id, bakery_name) values(new.id, coalesce(new.raw_user_meta_data->>'full_name','My Bakery')); insert into public.planner_settings(user_id) values(new.id); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
